version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_host
    env_file:
    - ./docker/mysql.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    - ./docker/db/entrypoint.sh:/entrypoint.sh
    ports:
    - 3306:3306

    
